<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="https://www.adlinktech.com/" target="_blank">{{ config.author }}</a><br>
    </div>
    <div id="footer-links">
      <a href="https://github.com/adlink" class="footer-link" target="_blank"><i class="fa fa-github-alt"></i></a>
    </div>
  </div>
</footer>
