<header id="header" class="wrapper">
  <div id="header-inner" class="inner">
    <h1 id="logo-wrap">
      <a href="{{ url_for_lang('') }}" id="logo">Hexo</a>
    </h1>
    <nav id="main-nav">
      {{ header_menu('main-nav') }}
      <a href="https://github.com/adlink" class="main-nav-link"><i class="fa fa-github-alt"></i></a>
      <div id="search-input-wrap">
        <div id="search-input-icon">
          <i class="fa fa-search"></i>
    </nav>
  </div>
</header>
